import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-gradient-to-r from-slate-800 to-cyan-900 min-h-screen p-2 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
